### ISSUE TITLE
themes: implement thread showing

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/valkyrie#139]
Deciding on how to display the thread might be important since it will probably need some clever logic or backend changes to support `queue || thread` data. But it depends on if we can get a thread thing working without extra changes

**Comment by icxes** [comment]
What's the actual problem here? The queue to thread link is probably how I'd do it this time too, it just kinda makes sense and keeps the page layout about the same with and without DJ, though just hiding the queue and putting the link somewhere else is an option too, especially on non-default themes.

**Comment by Wessie** [comment]
This is semi-implemented now in that we show the thread when the current streamer is not marked as a "Robot" in the system. Otherwise it shows the queue, it still needs some backend changes to actually support split-thread and queue updates though

**Comment by Wessie** [comment]
this is now implemented, `thread` and `queue` are now two separate event updates and it's up to the template to handle it potentially occupying the same space in the DOM
