### ISSUE TITLE
website/admin: currently playing song shows up on last played when saving profile in admin panel

### ISSUE THREAD

**Issue by icxes** [R-a-dio/valkyrie#150]
To reproduce, have the last played page and someone's profile page open. ~~Change "DJ text" on someone's profile~~, press "Save", switch to last played page and refresh. Last played log has multiple entries for the same song.

**Comment by Wessie** [comment]
because my dev env is down and I'll rather not forget later, the issue is the conditions in the functions here https://github.com/R-a-dio/valkyrie/blob/master/manager/api.go#L175 being reversed, both the user and the song one should be checking for a negative match (and probably only for their uniqueness sign, so the IDs and not the `EqualTo` the song is using)
